version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bugninja-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bugninja
      POSTGRES_USER: bugninja_user
      POSTGRES_PASSWORD: bugninja_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bugninja_user -d bugninja"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for queuing and real-time communication
  redis:
    image: redis:7-alpine
    container_name: bugninja-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./infrastructure/docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infrastructure/docker/frontend.Dockerfile
    container_name: bugninja-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount node_modules from host to avoid linter issues
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - redis
      - postgres
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: bugninja-network 